const API_URL = import.meta.env.VITE_API_URL ?? 'http://127.0.0.1:8000'
export type ImportRow = { id:number; row_number:number; raw_values:Record<string,string>; merchant_raw:string|null; merchant:string|null; amount:string|null; date:string|null; currency:string|null; fingerprint:string|null; status:string; error_reason:string|null; transaction_id:number|null; review_decision:string|null }
export type StagedImport = { id:number; filename:string; source:string; state:string; input_count:number; imported_count:number; duplicate_count:number; invalid_count:number; rejected_count:number; created_at:string; committed_at:string|null; parsing_ms:number; validation_ms:number; staging_ms:number; commit_ms:number; rows_per_second:string; peak_memory_bytes:number|null; rows:ImportRow[]; row_total:number; page:number; page_size:number }
export type Reconciliation = { import_id:number; state:string; input_count:number; imported_count:number; duplicate_count:number; invalid_count:number; rejected_count:number; accounted_count:number; reconciled:boolean; accepted_total:string; saved_total:string }
export type ColumnMapping = { date:string; merchant:string; amount:string|null; debit:string|null; credit:string|null; currency:string|null }
export async function importErrorMessage(response:Response){const body=await response.json().catch(()=>({})) as {detail?:string};return body.detail??'The import request failed.'}
export async function stageImport(token:string,file:File,mapping:ColumnMapping):Promise<StagedImport>{const form=new FormData();form.set('file',file);form.set('source','browser-upload');form.set('mapping',JSON.stringify(mapping));const response=await fetch(`${API_URL}/imports/upload`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});if(!response.ok)throw new Error(await importErrorMessage(response));return response.json() as Promise<StagedImport>}
export async function commitImport(token:string,id:number,decision:'import'|'reject'):Promise<Reconciliation>{const response=await fetch(`${API_URL}/imports/${id}/commit`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({possible_duplicates:decision})});if(!response.ok)throw new Error(await importErrorMessage(response));return response.json() as Promise<Reconciliation>}
export async function getImportPage(token:string,id:number,page:number):Promise<StagedImport>{const response=await fetch(`${API_URL}/imports/${id}?page=${page}&page_size=100`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(await importErrorMessage(response));return response.json() as Promise<StagedImport>}
export async function reviewImportRow(token:string,importId:number,rowId:number,decision:'approve'|'reject'):Promise<StagedImport>{const response=await fetch(`${API_URL}/imports/${importId}/rows/${rowId}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({decision})});if(!response.ok)throw new Error(await importErrorMessage(response));return response.json() as Promise<StagedImport>}
