// Express application factory: defines the browser-facing BFF without opening a network port.
import cors from 'cors';
import express, { type Request, type Response } from 'express';
import { randomUUID } from 'node:crypto';
import type { components } from './generated/spring-api.js';

type Fetch = typeof globalThis.fetch;
type TaskResponse = components['schemas']['TaskResponse'];
type CategoryResponse = components['schemas']['CategoryResponse'];
const correlationIdPattern = /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;

export interface AppOptions {
  fetch?: Fetch;
  springApiUrl?: string;
  springHealthUrl?: string;
  frontendOrigins?: string[];
}

export function createApp(options: AppOptions = {}) {
  const app = express();
  const fetchFromUpstream = options.fetch ?? globalThis.fetch;
  const renderSpringOrigin = process.env.SPRING_HOSTPORT ? `http://${process.env.SPRING_HOSTPORT}` : undefined;
  // Render gives the BFF a private host and port instead of a complete URL.
  const springApiUrl = options.springApiUrl ?? process.env.SPRING_API_URL ?? (renderSpringOrigin ? `${renderSpringOrigin}/api` : 'http://127.0.0.1:8080/api');
  const springHealthUrl = options.springHealthUrl ?? process.env.SPRING_HEALTH_URL ?? (renderSpringOrigin ? `${renderSpringOrigin}/actuator/health` : 'http://127.0.0.1:8080/actuator/health');
  const frontendOrigins = options.frontendOrigins ?? process.env.FRONTEND_ORIGIN?.split(',').map((origin) => origin.trim()).filter(Boolean) ?? ['http://127.0.0.1:5173', 'http://localhost:5173'];

  app.use(cors({ origin: frontendOrigins, exposedHeaders: ['X-Correlation-Id'] }));
  app.use(express.json());
  app.use((request, response, next) => {
    const suppliedId = request.header('x-correlation-id');
    const correlationId = suppliedId && correlationIdPattern.test(suppliedId) ? suppliedId : randomUUID();
    response.locals.correlationId = correlationId;
    response.setHeader('X-Correlation-Id', correlationId);
    response.on('finish', () => console.info(JSON.stringify({ correlationId, method: request.method, path: request.path, status: response.statusCode })));
    next();
  });

  function authorization(request: Request) {
    return request.header('authorization');
  }

  async function springRequest(path: string, request: Request, response: Response, body?: unknown) {
    const headers = new Headers();
    const token = authorization(request);
    if (token) headers.set('Authorization', token);
    // Forward the supplied ID or the ID generated by the BFF middleware.
    headers.set('X-Correlation-Id', response.locals.correlationId as string);
    if (body !== undefined) headers.set('Content-Type', 'application/json');
    return fetchFromUpstream(`${springApiUrl}${path}`, { method: request.method, headers, body: body === undefined ? undefined : JSON.stringify(body) });
  }

  async function forward(response: Response, upstream: globalThis.Response) {
    const contentType = upstream.headers.get('content-type');
    if (contentType) response.setHeader('Content-Type', contentType);
    const payload = await upstream.text();
    response.status(upstream.status).send(payload);
  }

  function upstreamJson<T>(response: globalThis.Response) {
    return response.json() as Promise<T>;
  }

  function requireBearerToken(request: Request, response: Response) {
    if (authorization(request)?.startsWith('Bearer ')) return true;
    response.status(401).json({ message: 'Bearer authentication is required' });
    return false;
  }

  app.post('/api/auth/:action', async (request, response, next) => {
    const action = (request.params as { action?: string }).action;
    if (action !== 'login' && action !== 'register') return response.status(404).json({ message: 'Authentication endpoint not found' });
    try { await forward(response, await springRequest(`/auth/${action}`, request, response, request.body)); }
    catch (error) { next(error); }
  });

  app.get('/health', async (_request, response) => {
    try {
      const upstream = await fetchFromUpstream(springHealthUrl);
      response.status(upstream.ok ? 200 : 503).json({ status: upstream.ok ? 'UP' : 'DOWN', upstream: await upstream.json() });
    } catch { response.status(503).json({ status: 'DOWN' }); }
  });

  app.get('/api/bootstrap', async (request, response, next) => {
    if (!requireBearerToken(request, response)) return;
    try {
      const [tasksResponse, categoriesResponse] = await Promise.all([
        springRequest('/tasks', request, response),
        springRequest('/categories', request, response),
      ]);
      if (!tasksResponse.ok) return forward(response, tasksResponse);
      if (!categoriesResponse.ok) return forward(response, categoriesResponse);
      response.json({
        tasks: await upstreamJson<TaskResponse[]>(tasksResponse),
        categories: await upstreamJson<CategoryResponse[]>(categoriesResponse),
      });
    } catch (error) { next(error); }
  });

  app.all(['/api/tasks', '/api/tasks/:id'], async (request, response, next) => {
    if (!requireBearerToken(request, response)) return;
    const id = (request.params as { id?: string }).id;
    try {
      await forward(response, await springRequest(id ? `/tasks/${id}` : '/tasks', request, response, ['POST', 'PUT'].includes(request.method) ? request.body : undefined));
    } catch (error) { next(error); }
  });

  app.all(['/api/categories', '/api/categories/:id'], async (request, response, next) => {
    if (!requireBearerToken(request, response)) return;
    const id = (request.params as { id?: string }).id;
    try {
      await forward(response, await springRequest(id ? `/categories/${id}` : '/categories', request, response, ['POST', 'PUT'].includes(request.method) ? request.body : undefined));
    } catch (error) { next(error); }
  });

  app.use((error: unknown, _request: Request, response: Response, _next: express.NextFunction) => {
    console.error('BFF request failed', error);
    response.status(502).json({ message: 'Unable to reach the task service' });
  });

  return app;
}
