# Generated by Django 5.2.7 on 2025-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_coordinator_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_food_safety',
            field=models.BooleanField(default=False),
        ),
    ]
