# Generated by Django 5.2.7 on 2025-12-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_event_requires_first_aid_event_requires_food_safety'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cultural_interests',
            field=models.ManyToManyField(blank=True, related_name='events', to='signups.culturalinterest'),
        ),
    ]
