# Generated by Django 5.2.7 on 2025-12-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0005_event_cultural_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='language_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=50),
        ),
    ]
