# Generated by Django 5.2.7 on 2025-12-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0007_certificate_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshift',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
