# Generated by Django 5.2.7 on 2025-11-05 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('capacity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0.0, help_text='Total volunteer hours logged manually.', max_digits=5)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.role')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signups.volunteer')),
            ],
            options={
                'unique_together': {('volunteer', 'role')},
            },
        ),
    ]
