# Generated by Django 5.2.7 on 2025-12-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_coordinator_culturalinterest_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
