# Generated by Django 5.2.7 on 2025-12-10 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0006_event_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='signups.event'),
        ),
    ]
