/*
Creating the physical schema for the EV Fleet and Market
Intelligence Platform in Microsoft Fabric Warehouse.

Design decisions:
- Using BIGINT surrogate keys generated by the data pipeline.
- Avoiding IDENTITY because it is currently a preview feature.
- Adding primary and foreign keys after creating the tables.
- Using NOT ENFORCED because Fabric Warehouse does not enforce keys.
- Validating relational integrity in the Python pipeline.
*/

CREATE TABLE dbo.fleet_operator
(
    fleet_operator_id BIGINT       NOT NULL,
    operator_name     VARCHAR(150) NOT NULL,
    industry          VARCHAR(100) NOT NULL,
    city              VARCHAR(100) NOT NULL,
    province          VARCHAR(100) NOT NULL,
    operating_region  VARCHAR(150) NOT NULL,
    operator_status   VARCHAR(20)  NOT NULL
);

ALTER TABLE dbo.fleet_operator
ADD CONSTRAINT pk_fleet_operator
PRIMARY KEY NONCLUSTERED (fleet_operator_id) NOT ENFORCED;

CREATE TABLE dbo.vehicle_model
(
    vehicle_model_id                  BIGINT        NOT NULL,
    manufacturer                      VARCHAR(100)  NOT NULL,
    model_name                        VARCHAR(150)  NOT NULL,
    model_year                        INT           NOT NULL,
    vehicle_class                     VARCHAR(100)  NULL,
    motor_power_kw                    DECIMAL(8, 2) NULL,
    battery_capacity_kwh              DECIMAL(8, 2) NULL,
    electric_range_km                 INT           NULL,
    energy_consumption_kwh_per_100_km DECIMAL(8, 2) NULL,
    recharge_time_hours               DECIMAL(6, 2) NULL
);

ALTER TABLE dbo.vehicle_model
ADD CONSTRAINT pk_vehicle_model
PRIMARY KEY NONCLUSTERED (vehicle_model_id) NOT ENFORCED;

ALTER TABLE dbo.vehicle_model
ADD CONSTRAINT uq_vehicle_model
UNIQUE NONCLUSTERED
(
    manufacturer,
    model_name,
    model_year
) NOT ENFORCED;